### PR TITLE
Use inspect to get coro state

### PR DESCRIPTION
**Pull request by laky55555**

### CODE REVIEW

**Comment by laky55555** [comment]
It looks like python 3.11 on ubuntu is having `f_lasti` equal to zero (maybe even not used anymore).
Replacing low-level internal checks with builtin from `inspect` library could potentially :crossed_fingers: make code a bit more robust

**Comment by kristjanvalur** [comment]
could you provide a test which fails which the PR fixes?  Also windows/ubuntu should not differ.

**Comment by laky55555** [comment]
The tests of old code against 3.11 should fail (on ubuntu 20.04 for sure as I'm running that locally) which I'm trying to verify with this [PR](https://github.com/kristjanvalur/py-asynkit/pull/4) but it looks like GitHub actions are running against python3.8 regardless of version. Will try to fix actions first
image

**Comment by laky55555** [comment]
The reason why the tests were passing for 3.11 is that all tests were running against 3.8 only instead of particular versions.

I updated the GitHub action to re-run against all listed python versions and you can see the failure on this "dummy" PR https://github.com/kristjanvalur/py-asynkit/pull/4. Feel free to close it on confirmation.

**Comment by kristjanvalur** [comment]
I see, my pip install was catching a pre-installed win 3.9 instead...  Thanks.   Verified that it also fails on windows as expected.  I'll merge this as-is, but will likely do some changes on top.  In particular, we don't really need the full build matrix, we only need windows to check that the Proactive loop works, so I'll probably just run the full suite on ubuntu plus 3.11 for windows.

**Comment by laky55555** [comment]
Thanks for merging 🙇

**Comment by kristjanvalur** [comment]
Yup, thanks for this.  Nice that someone is showing interest :)

**Comment by the-higgs** [comment]
Thanks for resolving the issue guys, any chance we can have v0.4.2 published in pip?

**Comment by kristjanvalur** [comment]
Sure.  I'm struggling a bit with my github actions...

**Comment by kristjanvalur** [comment]
Done, had accidentally disabled the publishing step.

**Pull request merged**
